In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
import pickle

In [2]:
df = pd.read_csv("train.csv")

In [3]:
df.head(4)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S

In [4]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [5]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [6]:
df = df.drop(['PassengerId','Name','Cabin', 'Embarked', 'Ticket'], axis = True)

In [7]:
df.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')

In [8]:
df.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
dtype: int64

In [9]:
df['Age'].fillna(df['Age'].mean(), inplace = True)

In [10]:
df.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
dtype: int64

In [11]:
df.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')

In [12]:
df_target = df.drop(['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare'], axis = 1)

In [13]:
df = df.drop(['Survived'], axis = 1)

In [14]:
df.head(3)

Pclass     Sex   Age  SibSp  Parch     Fare
0       3    male  22.0      1      0   7.2500
1       1  female  38.0      1      0  71.2833
2       3  female  26.0      0      0   7.9250

In [15]:
df.columns

Index(['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare'], dtype='object')

In [16]:
np.unique(df_target, return_counts = True)

(array([0, 1]), array([549, 342]))

In [17]:
np.unique(df['Pclass'], return_counts = True)

(array([1, 2, 3]), array([216, 184, 491]))

In [18]:
np.unique(df['Sex'], return_counts = True)

(array(['female', 'male'], dtype=object), array([314, 577]))

In [19]:
#np.unique(df['Age'], return_counts = True)

In [20]:
np.unique(df['SibSp'], return_counts = True)

(array([0, 1, 2, 3, 4, 5, 8]), array([608, 209,  28,  16,  18,   5,   7]))

In [21]:
np.unique(df['Parch'], return_counts = True)

(array([0, 1, 2, 3, 4, 5, 6]), array([678, 118,  80,   5,   4,   5,   1]))

In [22]:
#np.unique(df['Fare'], return_counts = True)

In [23]:
def tipo_Sex(line):
    if line == 'male' :
        return 'male'
    elif line == 'female':
        return 'female'

In [24]:
df['Sex']   = df['Sex'].apply(lambda x: tipo_Sex(x))

In [25]:
df_sex     = pd.get_dummies(df['Sex'], dummy_na=True)

In [26]:
df_sex.head()

female  male  NaN
0       0     1    0
1       1     0    0
2       1     0    0
3       1     0    0
4       0     1    0

In [27]:
df_sex.columns   = [ 'Female','Male', 'No_def_sex' ]

In [28]:
df_sex = df_sex.drop(['No_def_sex'], axis = 1)

In [29]:
df_sex.head()

Female  Male
0       0     1
1       1     0
2       1     0
3       1     0
4       0     1

In [30]:
df_ = pd.concat([df,df_sex ], axis=1, join="inner")

In [31]:
df_.head(4)

Pclass     Sex   Age  SibSp  Parch     Fare  Female  Male
0       3    male  22.0      1      0   7.2500       0     1
1       1  female  38.0      1      0  71.2833       1     0
2       3  female  26.0      0      0   7.9250       1     0
3       1  female  35.0      1      0  53.1000       1     0

In [32]:
df_ = df_.drop(['Sex'], axis = 1)

In [33]:
df_.head(3)

Pclass   Age  SibSp  Parch     Fare  Female  Male
0       3  22.0      1      0   7.2500       0     1
1       1  38.0      1      0  71.2833       1     0
2       3  26.0      0      0   7.9250       1     0

In [35]:
age = df_.drop(['Pclass','SibSp','Parch', 'Fare', 'Female', 'Male'], axis = 1)

In [36]:
y = df_target

In [37]:
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

In [68]:
min_max_scaler = preprocessing.MinMaxScaler()

In [69]:
x = df_
x = min_max_scaler.fit_transform(x)

In [70]:
dfx = pd.DataFrame(x)

In [71]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20)

In [72]:
dfy_train = pd.DataFrame(y_train)

In [73]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn import svm

In [74]:
clf = svm.SVC()

In [75]:
clf.fit(x_train, y_train)

/home/temporary/.local/lib/python3.6/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVC()

In [76]:
y_pred = clf.predict(x_test)

In [77]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix

In [78]:
accuracy_score(y_test, y_pred)

0.8212290502793296

In [79]:
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[108  11]
 [ 21  39]]
              precision    recall  f1-score   support

           0       0.84      0.91      0.87       119
           1       0.78      0.65      0.71        60

    accuracy                           0.82       179
   macro avg       0.81      0.78      0.79       179
weighted avg       0.82      0.82      0.82       179



In [80]:
#kernel

In [81]:
clf_precomputed = svm.SVC(kernel='precomputed')

In [82]:
gram_train = np.dot(x_train, x_train.T)

In [83]:
clf_precomputed.fit(gram_train, y_train)

/home/temporary/.local/lib/python3.6/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVC(kernel='precomputed')

In [84]:
gram_test = np.dot(x_test, x_train.T)

In [85]:
y_pred = clf_precomputed.predict(gram_test)

In [86]:
accuracy_score(y_test, y_pred)

0.7932960893854749

In [92]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='sigmoid')
svclassifier.fit(x_train, y_train)

/home/temporary/.local/lib/python3.6/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVC(kernel='sigmoid')

In [94]:
y_pred = svclassifier.predict(x_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[83 36]
 [22 38]]
              precision    recall  f1-score   support

           0       0.79      0.70      0.74       119
           1       0.51      0.63      0.57        60

    accuracy                           0.68       179
   macro avg       0.65      0.67      0.65       179
weighted avg       0.70      0.68      0.68       179



In [95]:
accuracy_score(y_test, y_pred)

0.6759776536312849

In [90]:
# save the model to disk

In [96]:
filename = 'titanic_model.sav'
pickle.dump(clf, open(filename, 'wb'))